
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbClassTest
{
    private readonly System.Collections.Generic.Dictionary<int, ClassTest> _dataMap;
    private readonly System.Collections.Generic.List<ClassTest> _dataList;
    
    public TbClassTest(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, ClassTest>();
        _dataList = new System.Collections.Generic.List<ClassTest>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            ClassTest _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = ClassTest.DeserializeClassTest(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, ClassTest> DataMap => _dataMap;
    public System.Collections.Generic.List<ClassTest> DataList => _dataList;

    public ClassTest GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ClassTest Get(int key) => _dataMap[key];
    public ClassTest this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

