
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class Tbreward
{
    private readonly System.Collections.Generic.Dictionary<int, reward> _dataMap;
    private readonly System.Collections.Generic.List<reward> _dataList;
    
    public Tbreward(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, reward>();
        _dataList = new System.Collections.Generic.List<reward>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            reward _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = reward.Deserializereward(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, reward> DataMap => _dataMap;
    public System.Collections.Generic.List<reward> DataList => _dataList;

    public reward GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public reward Get(int key) => _dataMap[key];
    public reward this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

