
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Children : Luban.BeanBase
{
    public Children(JSONNode _buf) 
    {
        { if(!_buf["m_name"].IsString) { throw new SerializationException(); }  MName = _buf["m_name"]; }
        { if(!_buf["age"].IsNumber) { throw new SerializationException(); }  Age = _buf["age"]; }
    }

    public static Children DeserializeChildren(JSONNode _buf)
    {
        return new Children(_buf);
    }

    public readonly string MName;
    public readonly int Age;
   
    public const int __ID__ = 1724170783;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "mName:" + MName + ","
        + "age:" + Age + ","
        + "}";
    }
}

}

