
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class enums_test : Luban.BeanBase
{
    public enums_test(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["equality"].IsNumber) { throw new SerializationException(); }  Equality = (item.EQuality)_buf["equality"].AsInt; }
    }

    public static enums_test Deserializeenums_test(JSONNode _buf)
    {
        return new enums_test(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    public readonly item.EQuality Equality;
   
    public const int __ID__ = -536847073;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "equality:" + Equality + ","
        + "}";
    }
}

}

