//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scenes/EventSystem/EventSystem_With_InputSystem/Controls4EventSystem.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Controls4EventSystem: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Controls4EventSystem()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controls4EventSystem"",
    ""maps"": [
        {
            ""name"": ""EventSystemControls"",
            ""id"": ""975b69de-4971-4c1d-9fbf-334172437882"",
            ""actions"": [
                {
                    ""name"": ""KeyActions"",
                    ""type"": ""Button"",
                    ""id"": ""0d77fb67-87ee-43b1-92d8-71dd7a171208"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""2c09134c-ecd8-4c36-957b-0381ca4bc900"",
                    ""path"": ""<Keyboard>/backquote"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""KeyActions"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // EventSystemControls
        m_EventSystemControls = asset.FindActionMap("EventSystemControls", throwIfNotFound: true);
        m_EventSystemControls_KeyActions = m_EventSystemControls.FindAction("KeyActions", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // EventSystemControls
    private readonly InputActionMap m_EventSystemControls;
    private List<IEventSystemControlsActions> m_EventSystemControlsActionsCallbackInterfaces = new List<IEventSystemControlsActions>();
    private readonly InputAction m_EventSystemControls_KeyActions;
    public struct EventSystemControlsActions
    {
        private @Controls4EventSystem m_Wrapper;
        public EventSystemControlsActions(@Controls4EventSystem wrapper) { m_Wrapper = wrapper; }
        public InputAction @KeyActions => m_Wrapper.m_EventSystemControls_KeyActions;
        public InputActionMap Get() { return m_Wrapper.m_EventSystemControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(EventSystemControlsActions set) { return set.Get(); }
        public void AddCallbacks(IEventSystemControlsActions instance)
        {
            if (instance == null || m_Wrapper.m_EventSystemControlsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_EventSystemControlsActionsCallbackInterfaces.Add(instance);
            @KeyActions.started += instance.OnKeyActions;
            @KeyActions.performed += instance.OnKeyActions;
            @KeyActions.canceled += instance.OnKeyActions;
        }

        private void UnregisterCallbacks(IEventSystemControlsActions instance)
        {
            @KeyActions.started -= instance.OnKeyActions;
            @KeyActions.performed -= instance.OnKeyActions;
            @KeyActions.canceled -= instance.OnKeyActions;
        }

        public void RemoveCallbacks(IEventSystemControlsActions instance)
        {
            if (m_Wrapper.m_EventSystemControlsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IEventSystemControlsActions instance)
        {
            foreach (var item in m_Wrapper.m_EventSystemControlsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_EventSystemControlsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public EventSystemControlsActions @EventSystemControls => new EventSystemControlsActions(this);
    public interface IEventSystemControlsActions
    {
        void OnKeyActions(InputAction.CallbackContext context);
    }
}
